### ISSUE TITLE
forkcms:install:prepare-for-reinstall not working

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2166]
## Type

- Non critical bug

## Problem description

> `bin/console forkcms:install:prepare-for-reinstall` is not working anymore

```
bin/console forkcms:install:prepare-for-reinstall

PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "kernel.project_dir". Did you mean one of these: "kernel.root_dir", "kernel.cache_dir", "kernel.logs_dir"? in /xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:84
Stack trace:
#0 /xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(134): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('kernel.project_...')
#1 /xxx/src/Backend/DependencyInjection/BackendExtension.php(21): Symfony\Component\DependencyInjection\Container->getParameter('kernel.project_...')
#2 /xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionCon in /xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 84

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "kernel.project_dir". Did you mean one of these: "kernel.root_dir", "kernel.cache_dir", "kernel.logs_dir"? in /xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:84
Stack trace:
#0 /xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(134): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('kernel.project_...')
#1 /xxx/src/Backend/DependencyInjection/BackendExtension.php(21): Symfony\Component\DependencyInjection\Container->getParameter('kernel.project_...')
#2 /xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionCon in /xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 84
```

**Comment by carakas** [comment]
I used this all the time, it should work :s

**Comment by jeroendesloovere** [comment]
## Description
The installer of fork was crashed => fixed by https://github.com/forkcms/forkcms/pull/2165
And then some things were broken, including the reinstaller.

## Proposed solutions

Is there a way to set the `kernel.project_dir` earlier in the installer script,
so everybody can reinstall things when one or more modules were broken during installation.

**Comment by carakas** [comment]
did you clear all your cache?

**Comment by carakas** [comment]
and do a composer install?

**Comment by carakas** [comment]
closed because it is invalid, has to do with still having fork 4 cache
